name: Arduino Size Deltas

on:
  workflow_call:
    inputs:
      reports-path:
        required: false
        type: string
        default: sketches-reports

jobs:
  compute:
    runs-on: ubuntu-latest
    steps:
      - name: Download sketches reports artifact
        uses: actions/download-artifact@v8
        with:
          pattern: arduino-deltas-*
          path: ${{ inputs.reports-path }}

      - uses: 2bndy5/arduino-report-size-deltas@59d8b37b161ef638a7b326ba1bd3a17e33ace237 # v1.2.1
        with:
          sketches-reports-source: ${{ inputs.reports-path }}
