name: Run PlatformIO in CI

on:
  workflow_call:
    inputs:
      example-path:
        required: true
        type: string
      board-id:
        required: true
        type: string
      build-flags:
        default: ""
        required: false
        type: string
        description: |
          A space delimited string of build flags to pass to the `pio ci command`.
          This value is passed as env var PLATFORMIO_BUILD_FLAGS.
          See docs at
             https://docs.platformio.org/en/latest/envvars.html#envvar-PLATFORMIO_BUILD_FLAGS
      lib-deps:
        required: false
        type: string
        description: |
          A space delimited string of lib names to install as extra dependencies.
          UPDATE: Each lib specified should be prefixed with a `-l ` like so: `-l <lib_spec>`.
             This also allows for extra tools/frameworks/etc. See docs at
             https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_install.html
          NOTE: RF24 dependencies are automatically installed accordingly.
      rf24-ref:
        required: false
        type: string
        default: master
        description: git ref of the RF24 lib dependency
      rf24network-ref:
        required: false
        type: string
        default: master
        description: git ref of the RF24Network lib dependency
      rf24mesh-ref:
        required: false
        type: string
        default: master
        description: git ref of the RF24Mesh lib dependency
      build_flags:
        description: 'Optional build flags for PlatformIO'
        required: false
        type: string

permissions: {}

jobs:
  run_pio:
    # We must use a windows runner because ESP SDK ships with pre-compiled libs.
    # These pre-compiled libs come with LwIP lib (used by RF24Ethernet) included,
    # but LwIP lib is disabled by default on Linux builds.
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: project
          persist-credentials: false

      - name: Cache pip
        uses: actions/cache@v5
        with:
          path: |-
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio-${{ inputs.board-id }}-${{ inputs.example-path }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Get lib info
        id: lib-info
        shell: bash
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |-
          rf24_deps=''
          if [[ "${REPO_NAME}" == 'RF24Mesh' ]]; then
            rf24_deps=RF24Network
          elif [[ "${REPO_NAME}" == 'RF24Ethernet' ]]; then
            rf24_deps='RF24Network;RF24Mesh'
          fi
          echo "rf24-deps=$rf24_deps" >> "${GITHUB_OUTPUT}"

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Install extra dependencies
        if: inputs.lib-deps != ''
        shell: bash
        env:
          LIB_DEPS: ${{ inputs.lib-deps }}
        run: pio pkg install -g ${LIB_DEPS}

      - name: Checkout RF24Mesh library dependency
        if: contains(steps.lib-info.outputs.rf24-deps, 'RF24Mesh') && !endsWith(github.repository, 'RF24Mesh')
        uses: actions/checkout@v6
        with:
          path: RF24Mesh
          repository: nRF24/RF24Mesh
          ref: ${{ inputs.rf24mesh-ref }}
          persist-credentials: false

      - name: Checkout RF24Network library dependency
        if: contains(steps.lib-info.outputs.rf24-deps, 'RF24Network') && !endsWith(github.repository, 'RF24Network')
        uses: actions/checkout@v6
        with:
          path: RF24Network
          repository: nRF24/RF24Network
          ref: ${{ inputs.rf24network-ref }}
          persist-credentials: false

      - name: Checkout RF24 library dependency
        if: endsWith(github.repository, 'RF24') == false
        uses: actions/checkout@v6
        with:
          path: RF24
          repository: nRF24/RF24
          ref: ${{ inputs.rf24-ref }}
          persist-credentials: false

      - name: Inject build flags into env
        if: inputs.build-flags != ''
        shell: bash
        env:
          BUILD_FLAGS: ${{ inputs.build-flags }}
        run: echo "PLATFORMIO_BUILD_FLAGS=${BUILD_FLAGS}" >> "${GITHUB_ENV}"

      - name: Run PlatformIO
        shell: bash
        working-directory: project
        env:
          PLATFORMIO_CI_SRC: ${{ inputs.example-path }}
          BOARD: ${{ inputs.board-id }}
        run: >-
          pio ci
          --board="${BOARD}"
          --lib="."
          ${{ !endsWith(github.repository, 'RF24') && '--lib=../RF24' || '' }}
          ${{ contains(steps.lib-info.outputs.rf24-deps, 'RF24Network') && '--lib=../RF24Network' || ''}}
          ${{ contains(steps.lib-info.outputs.rf24-deps, 'RF24Mesh') && '--lib=../RF24Mesh' || ''}}
