name: Get latest version

on:
  workflow_call:
    outputs:
      latest:
        description: The latest released version number.
        value: ${{ jobs.get-version.outputs.lib-version }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      lib-version: ${{ steps.latest_ver.outputs.release }}
    steps:
      - uses: actions/checkout@v3
      - name: get latest release version number
        id: latest_ver
        run: echo "release=$(awk -F "=" '/version/ {print $2}' library.properties)" >> $GITHUB_OUTPUT
